

STR = "WHOREGION,FLUSEASON,HEMISPHERE,ITZ,COUNTRY_CODE,COUNTRY_AREA_TERRITORY,ISO_WEEKSTARTDATE,ISO_YEAR,ISO_WEEK,MMWR_WEEKSTARTDATE,MMWR_YEAR,MMWR_WEEK,ORIGIN_SOURCE,SPEC_PROCESSED_NB,SPEC_RECEIVED_NB,AH1N12009,AH1,AH3,AH5,AH7N9,ANOTSUBTYPED,ANOTSUBTYPABLE,AOTHER_SUBTYPE,AOTHER_SUBTYPE_DETAILS,INF_A,BVIC_2DEL,BVIC_3DEL,BVIC_NODEL,BVIC_DELUNK,BYAM,BNOTDETERMINED,INF_B,INF_ALL,INF_NEGATIVE,ILI_ACTIVITY,ADENO,BOCA,HUMAN_CORONA,METAPNEUMO,PARAINFLUENZA,RHINO,RSV_PROCESSED,RSV,OTHERRESPVIRUS,OTHER_RESPVIRUS_DETAILS,LAB_RESULT_COMMENT,WCR_COMMENT,ISO2,ISOYW,MMWRYW,PSOURCE_SUBTYPE_INF,PSOURCE_PPOS_INF,PSOURCE_RSV"

f = open("headers.txt","w+")

headers = STR.split(",")
for i in headers:
    f.write(i)
    f.write("\n")

f.close()